### ISSUE TITLE
"Unable to open audio device: DirectSound CreateSoundBuffer: Unsupported audio format"

### ISSUE THREAD

**Issue by josswright** [8bitbubsy/pt2-clone#12]
I just installed `pt2-clone` on a fairly fresh Windows 10 install on a new Thinkpad P1 Gen 2 laptop.

The system is connected to a few audio devices. `pt2-clone` works fine on the internal (Synaptics) audio, and on my monitor's USB speakers (Dell AC511 USB SoundBar). If I am using my Focusrite Scarlett 6i6 USB audio interface, though, I get the error in the title:

`Unable to open audio device: DirectSound CreateSoundBuffer: Unsupported audio format`

**Comment by 8bitbubsy** [comment]
Strange. PT2 will open a 16-bit 48000Hz stereo audio stream per default. This ought to work on almost any configuration. Maybe it wants 24/32 bits only, or below or above 48kHz? I've never seen this issue before.

**Comment by josswright** [comment]
I thought it might be the sample rate, so I installed the Focusrite controller software, which asked me to reboot. On reboot, this now seems to work. Maybe it was just a glitch, or maybe the official drivers were required. Either way, it seems to be working now.

**Comment by DROWSYNET** [comment]
Having the same issue on an HP Spectre using a Scarlett 18i20 and a Zoom U44 @ 48khz 16-bit. How exactly does PT2 communicate with Windows audio?

**Comment by 8bitbubsy** [comment]
It uses SDL2 and tries to open a 16-bit PCM 48kHz stereo stream per default. Did you try to install the Focusrite controller software like josswright did? It seemed to work for him.

**Comment by DROWSYNET** [comment]
Yep, that did it. W10 said 48khz, Focusrite said 96khz. Must have been some disconnect between the two. What does SDL2 look for when it's unable to create a soundbuffer? Is it checking for blocks from other programs ie. ASIO4ALL? Does it know how to upsample the stream to a higher bitrate / sample rate?

**Comment by 8bitbubsy** [comment]
Not sure, but there's some info here: https://wiki.libsdl.org/SDL_OpenAudioDevice
