### ISSUE TITLE
pt2-clone disables screensaver

### ISSUE THREAD

**Issue by xenium1024** [8bitbubsy/pt2-clone#14]
I've noticed that when I have pt2-clone running it disables my screensaver. Since I sometimes leave it running on a CRT to just listen to mod files, I worry about phosphor burn. (Come on, I'm not the only one running this on a CRT, right? Hehehe.) ;-)

I didn't see anything in the source related to this so I did some research and found that this is now the default behavior for the SDL library, so you would have to explicitly tell SDL not to disable the screensaver on startup via a simple call to SDL_EnableScreensaver().

Any chance this could be added to a future release?

My phosphors thank you in advance. :-)

Love pt2-clone btw!

**Comment by 8bitbubsy** [comment]
I fixed this right now, but I'm not sure when I will release a new version.

**Comment by xenium1024** [comment]
That has to be the world record for fastest bug fix ever. Thanks! :-)

No worries on the release, I'll give a try at compiling it.

**Comment by xenium1024** [comment]
I just successfully compiled it and can confirm my screensaver works again even when it's playing full screen. Awesome.

Thanks Bubsy!

**Comment by 8bitbubsy** [comment]
> Thanks Bubsy!
It's 8bitbubsy. ;)
