### ISSUE TITLE
Sample Editor: mix only takes decimal numbers instead of hex numbers

### ISSUE THREAD

**Issue by chrisly42** [8bitbubsy/pt2-clone#15]
Hi. I'm using the great pt2-clone 1.27 for MacOS (thank you!). In the Edit Op./3 Panel, when using the MIX button, the pop up line for the selection which samples to mix only allows me to enter the sample numbers in decimals (using digits 0-9). This makes it impossible to select the samples 0a-0f and 1a-1f neither as source nor target.

One can work around this issue by exchanging samples first in the Edit Op./2 Panel, but a fix would be great nonetheless.

**Comment by 8bitbubsy** [comment]
I fixed this now. I'll release a new version of the PT2 clone soon.

**Comment by chrisly42** [comment]
Awesome! Thank you.
