### ISSUE TITLE
build on raspberry pi/raspbian

### ISSUE THREAD

**Issue by sphaero** [8bitbubsy/pt2-clone#2]
Just wanted to drop that it runs fine on a Raspberry Pi as long as you build it using cmake. The make-linux.sh scripts gives a binary which segfaults. Can't trace what's wrong with it, probably some compiler flag.

Tested on Raspbian GNU/Linux 10 (buster) on a RPI3B without Xorg.
```
mkdir build
cd build/
cmake ..
make
```
Tested with a mod file which ran smooth.

**Comment by sphaero** [comment]
Ha, hadn't noticed there's a debian package. :man_facepalming: Tested it and it works fine as well. (tested without X)
![IMG_20191218_121158](https://user-images.githubusercontent.com/832465/71089332-e9402300-21a0-11ea-8c8b-2f677288ca33.jpg)

**Comment by 8bitbubsy** [comment]
I don't know what would cause that, and I don't know what to do because modifying that make script to make it work for Raspberry Pi could break it for other systems/distros.

**Comment by alexmyczko** [comment]
how do you run it? i mean without x but with what instead?

**Comment by sphaero** [comment]
I wouldn't worry about it. It works if you go the cmake route. I'm running it directly on the rpi from the console. SDL is able to open a window through what was once referred to as dispmanX. Not sure what's it's called now. It might be some calls coming from openGL ES.
