### ISSUE TITLE
Mouse Pointer

### ISSUE THREAD

**Issue by Freefire666** [8bitbubsy/pt2-clone#23]
Hi 
is there a way to use my original mouse pointer in the program.
can add you a line to the config for use this feature?

have a nice day :)

**Comment by 8bitbubsy** [comment]
Hi, not yet. I actually added this feature to the FT2 clone not long ago. However, in PT2 the color of the mouse color is important. It tells what state the tracker is currently in (edit, record, yes/no dialog open, action aborted, etc) so I think it's not a good idea to remove it. I can probably add a config entry for this in the future...
