### ISSUE TITLE
Top-rightmost pixel quit in full-screen

### ISSUE THREAD

**Issue by MrSVCD** [8bitbubsy/pt2-clone#25]
Hi
I have a feature request and that is that the top-rightmost pixel on my monitor also be the the quit pixel in full-screen mode. 
I use integer scaling and therefore the nice pixels don't stretch to that corner on my 16:9 monitor.
I hope this is not hard to implement but it is over my head.

**Comment by 8bitbubsy** [comment]
Please note that I did a second commit to fix a mistake in the first one, just in case you're going to compile the clone before a new version is out.
