### ISSUE TITLE
Alt+F11 not working

### ISSUE THREAD

**Issue by Some1NamedNate** [8bitbubsy/pt2-clone#29]
I tried to toggle to the real VU meter in version 1.51 but it won't work.

**Comment by 8bitbubsy** [comment]
It works fine here on Windows, not sure what could be the issue. Do you use macOS? If so, maybe you need to change some keybindings in your OS settings.

**Comment by Some1NamedNate** [comment]
I'm on Windows.

**Comment by 8bitbubsy** [comment]
Do you have Geforce Experience installed (with your GPU driver)? That could be occupying the keybinding. Try to look in the Geforce Experience keybinding settings.

**Comment by 8bitbubsy** [comment]
Was it related to Geforce Experience?

**Comment by Some1NamedNate** [comment]
Yes it was.
