### ISSUE TITLE
Master Soundtracker mod not playing correctly

### ISSUE THREAD

**Issue by bryc** [8bitbubsy/pt2-clone#3]
The snare is going crazy in position 2! Seems to be mixed with the bass for some reason in channel 2. Here's the mod: [bug-toalettpapir.zip](https://github.com/8bitbubsy/pt2-clone/files/4195226/bug-toalettpapir.zip)

Apparently it has 2 versions and this one doesn't have that issue: [bug-stein.zip](https://github.com/8bitbubsy/pt2-clone/files/4195268/bug-stein.zip). This one isn't without issue either. At pos 14, in channel 2 the synth lead cuts out in volume at the end of the sample when it should not.

**Comment by 8bitbubsy** [comment]
Did one simple fix to fix both, and it should also fix plenty of others. Thanks!

**Comment by 8bitbubsy** [comment]
I forgot to mention, but I am updating the releases on 16-bits.org too. I try to not make changes to the releases like that, but since it has only been a few hours I'll do it. This is also a crucial fix.

**Comment by 8bitbubsy** [comment]
Done.
