### ISSUE TITLE
any sample created by this protracker has a blank byte at the beginning

### ISSUE THREAD

**Issue by retro-64K** [8bitbubsy/pt2-clone#31]
title says it all, i wanna make simple waveform samples but no matter what i do, when i hit the save button and load it again, there's a blank byte at the beginning, which makes a straight line on my sample and partially messes it up. also, when i try adding a loop, protracker also can't save the loop, so if i load the sample again i have to manually fix the waveform and enable the loop again.

**Comment by 8bitbubsy** [comment]
That's because non-looped samples _require_ the first two bytes of the sample to be blank, or else it will emit an infinite beep after the sample has been played. Just set the save type to WAV, and it will attach the loop points in the WAV on save (and also acquire them on load).

**Comment by retro-64K** [comment]
oh, that infinite beep thing already happened to me before and i thought something else triggered it. so these first 2 bytes are necessary on the raw samples in order to fix this beeping. what about on .iff files? is it the same thing? i have little knowledge on .iff file types, so i apologize if that's a stupid question lol

**Comment by 8bitbubsy** [comment]
The beep has nothing to do with the sample format after saving, it's a behavior internally in ProTracker itself.
You can safe as IFF too if you want, it will also store the loop information in it.

**Comment by retro-64K** [comment]
nice, thanks for the explanation!
