### ISSUE TITLE
protracker.ini isn't loaded when protracker is launched from a file

### ISSUE THREAD

**Issue by retro-64K** [8bitbubsy/pt2-clone#32]
if i open protracker, and select the module i wanna edit/ play, it obviously loads protracker.ini first as it should, but if i right click on a module and select "open with..." and then choose protracker, protracker loads but without protracker.ini, so it uses its default settings instead.

**Comment by retro-64K** [comment]
oh yeah, i also noticed that when i open the module on protracker the other way, not only it doesn't load protracker.ini, the window title also changes from "ProTracker 2 clone v1.55" to "ProTracker 2 clone v1.50" for some reason.

**Comment by 8bitbubsy** [comment]
Not sure what OS you use, but protracker.ini is getting loaded when I double-click on .MODs associated with the PT2 clone EXE in Windows, so no problems here. Also, if you get a different version ion the window title, then it suggests that you have an earlier version floating around somewhere on your drive that is being used for some reason.

**Comment by retro-64K** [comment]
> Not sure what OS you use
oh yeah, forgot to mention that, currently using windows 10.
> if you get a different version in the window title, then it suggests that you have an earlier version floating around somewhere on your drive that is being used for some reason.
yeah, for some VERY ODD REASON, because i'm explicitly choosing v1.55 when i open the file with protracker.

**Comment by retro-64K** [comment]
so now the problem was windows itself and not protracker. even though i was clearly choosing the latest version, windows insisted on using the earliest version i had, v1.50, which had the default settings. now i deleted the old versions and kept only the latest one (v1.55).
damn you, windows >:(

**Comment by 8bitbubsy** [comment]
Yeah, this is why I recommend just overwriting the EXE (and SDL2.DLL if needed) in the directory when you update to a newer version, don't put different versions in different directories. I'm glad you sorted it out, though.
