### ISSUE TITLE
Placement and contents of `protracker.ini`

### ISSUE THREAD

**Issue by asbjornu** [8bitbubsy/pt2-clone#33]
The README mentions a `protracker.ini` file, but not where it's supposed to be placed on the file system, nor what its (full) contents is supposed to be. More information on this file would be highly appreciated! 🙏🏼 😃

**Comment by 8bitbubsy** [comment]
I updated `README.md` now to include information about this.

**Comment by asbjornu** [comment]
Excellent, thanks!
