### ISSUE TITLE
[Feature Request] Add double-size mode

### ISSUE THREAD

**Issue by VanessaE** [8bitbubsy/pt2-clone#36]
For those of us with larger screens and/or bad eyes, I think it would be a good idea to offer a double-size mode, or anyway allow resizing the window (the contents would just scale up/down linearly, of course).

**Comment by 8bitbubsy** [comment]
Take a look at VIDEOSCALE in protracker.ini.

**Comment by VanessaE** [comment]
Oh I totally missed the .ini
