### ISSUE TITLE
[bug] Not starting

### ISSUE THREAD

**Issue by nrkceg2** [8bitbubsy/pt2-clone#39]
For some odd reason, pt2 clone isn't starting for me, it used to pull up SmartScreen, but after disabling SmartScreen thru regedit, it starts the application for a brief moment in the background, then closes. It used to work fine a few months ago, but as of somewhat recently, it just doesn't start.

**Comment by 8bitbubsy** [comment]
Hm, odd. Did you make sure to overwrite both SDL2.DLL and protracker.ini (you shouldn't have needed this, but maybe there's something old in there crashing the config loader) when copying the files from the release zip?

**Comment by nrkceg2** [comment]
it was a completely fresh install downloaded from your website, whenever I download a new version I usually just extract it separate from a previous install in case of something like this happening but i recently reinstalled windows and this happened, so i have no backup to fall back to. I've tried removing protracker.ini and redownloading in its entirety.

**Comment by 8bitbubsy** [comment]
OK. I’ll try to look into it next week.

**Comment by nrkceg2** [comment]
Alright, thanks!

**Comment by 8bitbubsy** [comment]
Can you try to download the new version (v1.72) from https://16-bits.org/pt2.php and try again? I didn't find any problems (runs without crashing here), but I updated SDL2, maybe it helps.

**Comment by nrkceg2** [comment]
Alright! I'll be sure to try that when I get home.

**Comment by nrkceg2** [comment]
tried it just now, now it (for some reason) starts twice, but still doesn't open. Freshly downloaded install too; will check for anything wrong on my end.

**Comment by 8bitbubsy** [comment]
Weird... I can't trigger this bug, so I'm unsure how I'm going to fix the issue.

**Comment by nrkceg2** [comment]
Apparently it seems to be occurring because my copy of windows is heavily modified(?)
Here's the Event Viewer logs.

Faulting application name: pt2-clone-win64.exe , version: 1.0.0.0, time stamp: 0x6762c3ba
Faulting module name: ntdll.dll, version: 10.0.19041.1288, time stamp: 0xa280d1d6
Exception code: 0xc0000005
Fault offset: 0x000000000001aa5f
Faulting process id: 0x1cb0
Faulting application start time: 0x01db527b83811bb7
Faulting application path: c:\users\classic\desktop\pt2-clone 1.72\pt2-clone-win64.exe 
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: b8a6ba38-50ff-435f-82e1-0ba898427c6e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by nrkceg2** [comment]
I use a Windows 10 ISO called classic7 for reference, it makes extensive use of programs like WindHawk to inject stuff into various windows dlls, in this case to make Windows 10 look pretty much 1:1 with Windows 7. Might be a classic7 issue, will look into on my end.

**Comment by 8bitbubsy** [comment]
Hm, I see. I'm going to install classic7 on a laptop and try to debug it there (if it crashes at all). This could end up being a waste of time if it's actually a problem with some DLL functions because of classic7, but if it's a bug in the PT2 clone then it's worth it trying to fix it. :)

**Comment by 8bitbubsy** [comment]
OK, so the PT2 clone runs fine in the latest version of classic7. I did a clean install without changing anything.

**Comment by nrkceg2** [comment]
Maybe it's just because I'm running a slightly outdated build. I'll try upgrading from my current one soon.

**Comment by nrkceg2** [comment]
it works now!
Have no clue what fixed it; but it works!
