### ISSUE TITLE
Config file location (feature request)

### ISSUE THREAD

**Issue by skope2v** [8bitbubsy/pt2-clone#40]
Hi! For Linux (and probably also Mac and other Unixish systems) is it possible to have PT-clone check for config files in ~/.config/protracker in addition to ~/.protracker? This is where most configs usually end up and leaves a cleaner home directory. (:

**Comment by 8bitbubsy** [comment]
Will add this very soon.

**Comment by 8bitbubsy** [comment]
This was added now, can you test if it works for me?

**Comment by skope2v** [comment]
Great! Yes, I'll test it this evening after work.

**Comment by skope2v** [comment]
Hi again. This is to confirm protracker.ini is now being read from ~/.config/protracker/ without any issues. Thank you. (:

**Comment by 8bitbubsy** [comment]
Great!
