### ISSUE TITLE
Support for PPC machine ?

### ISSUE THREAD

**Issue by BeWorld2018** [8bitbubsy/pt2-clone#5]
Hi,
If is possible to compile on MorphOS and AmigaOS4 ?
Thanks

**Comment by 8bitbubsy** [comment]
No, sorry, big endianness is not supported. I doubt MorphOS nor AmigaOS4 has SDL2 ports either.

**Comment by BeWorld2018** [comment]
Yes SDL2 work fine on AmigaOS4 and MorphOS !!!

See bug here :

in pt2_modloader.c : 

fread(&powerPackerID, 4, 1, f);
	if (powerPackerID == 0x30325850) // "PX20"

all m#?()  doesnt support bigendian

**Comment by 8bitbubsy** [comment]
There are plentiful of cases where big endian will fail in the clone, and I removed all of the old big endian-specific code long ago because I don't want to spend more time and resources supporting PPC. I don't have any test machines with PPC for testing either.

**Comment by BeWorld2018** [comment]
ok, I understand but it's a shame for the Amiga community. Thanks anyway for answering me.

**Comment by 8bitbubsy** [comment]
That's not very nice to hear... Remember that this is a non-profit project, and I have worked really hard on it. I hope that the Amiga community can see a value in my PT clone even if it doesn't run on PPC. I'd guess that most users in the Amiga community are not using a PPC in their main computer either...

**Comment by BeWorld2018** [comment]
ok sorry.. english is not my primary language... maybe wrong word :(
Your work is fantastic !
