### ISSUE TITLE
pt2-clone: ftbfs with GCC-10

### ISSUE THREAD

**Issue by alexmyczko** [8bitbubsy/pt2-clone#7]
Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957718

**Comment by 8bitbubsy** [comment]
I don't really understand how this happens, as `#pragma once` should make sure that the header is only included and parsed one time, as far as I know. Maybe using struct data in headers is not really C compliant, and that the later GCC versions are even more strict.

**Comment by 8bitbubsy** [comment]
Talked to someone now, and the way I do it is completely wrong. I'll refactor the code a bit and come with a fix.

**Comment by 8bitbubsy** [comment]
Fixed.
