### ISSUE TITLE
saving mod doesn't preserve bpm

### ISSUE THREAD

**Issue by sphaero** [8bitbubsy/pt2-clone#9]
Just create a simple mod, set a non 125 bpm, save the file, clear everything and load the file. The BPM will be 125bpm again.

**Comment by 8bitbubsy** [comment]
ProTracker doesn't save the BPM, that's just how it is.

**Comment by sphaero** [comment]
ow, really. I can't recall. How are they set in all the other mods then?

**Comment by 8bitbubsy** [comment]
Later versions of Ultimate Soundtracker (and the rest of the Soundtracker series) has a BPM CIA field in the .mod header, but this is not used in ProTracker. If you mean other formats like XM/IT, then there are specific fields in the header for this.

**Comment by sphaero** [comment]
my god this is bringing back memories :). Haha, thanks. Closing this
